import {
	ArrowLeftCircleIcon,
	ArrowRightCircleIcon,
	ArrowsPointingInIcon,
	ArrowsPointingOutIcon,
	Bars3Icon,
	BellIcon,
	CheckIcon,
	ChevronDownIcon,
	ChevronUpIcon,
	Cog6ToothIcon,
	CurrencyDollarIcon,
	EyeIcon,
	EyeSlashIcon,
	HomeIcon,
	MagnifyingGlassIcon,
	MinusCircleIcon,
	MoonIcon,
	PlusCircleIcon,
	SunIcon,
	XMarkIcon,
} from "@heroicons/react/24/outline";

export const icons = {
	outline: {
		bell: <BellIcon />,
		eye: <EyeIcon />,
		eye_slash: <EyeSlashIcon />,
		search: <MagnifyingGlassIcon />,
		chevron_down: <ChevronDownIcon />,
		chevron_up: <ChevronUpIcon />,
		home: <HomeIcon />,
		gear: <Cog6ToothIcon />,
		arrow_right_circle: <ArrowRightCircleIcon />,
		arrow_left_circle: <ArrowLeftCircleIcon />,
		minus_circle: <MinusCircleIcon />,
		plus_circle: <PlusCircleIcon />,
		arrows_pointing_in: <ArrowsPointingInIcon />,
		arrows_pointing_out: <ArrowsPointingOutIcon />,
		bars_3: <Bars3Icon />,
		x: <XMarkIcon />,
		sun: <SunIcon />,
		moon: <MoonIcon />,
		dollar: <CurrencyDollarIcon />,
		check: <CheckIcon />,
	},
};
